ath10k-ct: switch to version 5.4 on kernel 5.4
ath10k-ct 5.4 is required for kernel 5.4
as 4.19 produces build errors:

/home/kvdp/git/openwrt_staging/build_dir/target-arm_cortex-a9+neon_musl_eabi/
linux-imx6/ath10k-ct-regular/ath10k-ct-2020-01-29-b7297ab4/ath10k-4.19/mac.c
:6066:23: error: implicit declaration of function 'dma_zalloc_coherent';
did you mean 'dma_alloc_coherent'? [-Werror=implicit-function-declaration]

   arvif->beacon_buf = dma_zalloc_coherent(ar->dev,
                       ^~~~~~~~~~~~~~~~~~~
                       dma_alloc_coherent
/home/kvdp/git/openwrt_staging/build_dir/target-arm_cortex-a9+neon_musl_eabi/
linux-imx6/ath10k-ct-regular/ath10k-ct-2020-01-29-b7297ab4/ath10k-4.19/mac.c
:6066:21: warning: assignment to 'void *' from 'int' makes pointer from
integer without a cast [-Wint-conversion]
   arvif->beacon_buf = dma_zalloc_coherent(ar->dev,
                     ^

Signed-off-by: Koen Vandeputte <koen.vandeputte@ncentric.com>